# Generated by Django 5.1.3 on 2025-09-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_solicitud_delete_producto"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="facultad",
            field=models.CharField(default="Ingeniería", max_length=100),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="titulacion",
            field=models.CharField(
                default="Curso de Adaptación al Grado en Ingeniería Informática",
                max_length=100,
            ),
        ),
    ]
