# Generated by Django 5.1.3 on 2025-09-02 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_solicitud_facultad_solicitud_titulacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facultad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="facultad",
            field=models.ForeignKey(
                default="Facultad de Ciencias",
                on_delete=django.db.models.deletion.PROTECT,
                to="inventario.facultad",
            ),
        ),
    ]
