# Generated by Django 5.1.3 on 2025-09-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0004_facultad_alter_solicitud_facultad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Titulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "cod_facultad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.facultad",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="titulacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventario.titulacion"
            ),
        ),
    ]
