# Generated by Django 5.1.3 on 2025-09-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_titulacion_alter_solicitud_titulacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="grupo_deseado",
            field=models.CharField(default="Grupo 1", max_length=10),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="turno_deseado",
            field=models.CharField(default="Tarde", max_length=10),
        ),
        migrations.AddField(
            model_name="solicitud",
            name="workflow_json",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobado", "Aprobado"),
                    ("rechazado", "Rechazado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
