# Generated by Django 5.1.3 on 2025-09-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0006_solicitud_grupo_deseado_solicitud_turno_deseado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="titulacion",
            name="cod_facultad",
        ),
    ]
