# Generated by Django 5.1.3 on 2025-09-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0007_remove_titulacion_cod_facultad"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="observaciones",
            field=models.CharField(default="--", max_length=400),
        ),
    ]
